from enum import Enum
class ServiceError(Enum):
    ERROR_USER_EXISTS = 1
    ERROR_USER_NOT_FOUND = 2
    ERROR_USER_NO_PIN = 3
    ERROR_USER_INVALID_PIN = 4
    ERROR_DURING_CONFIRMATION = 5
    ERROR_DURING_DEVICE_REGISTRATION = 6
    ERROR_NO_PENDING_CONFIRMATIONS = 7